wandb_version: 1

name:
  desc: null
  value: deepspeech
n_gpu:
  desc: null
  value: 1
preprocessing:
  desc: null
  value:
    sr: 22050
    spectrogram_params: {}
    log_spec: false
augmentations:
  desc: null
  value:
    wave: []
    spectrogram: []
generator_model:
  desc: null
  value:
    type: Generator
    args:
      h_u: 256
      k_u:
      - 16
      - 16
      - 8
      k_r:
      - 3
      - 5
      - 7
      D_rs:
      - - - 1
        - - 2
      - - - 2
        - - 6
      - - - 3
        - - 12
      l_relu_slope: 0.1
discriminator_model:
  desc: null
  value:
    type: Discriminator
    args:
      k_msd: 3
      periods_mpd:
      - 2
      - 3
      - 5
      - 7
      - 11
      l_relu_slope: 0.1
data:
  desc: null
  value:
    train:
      batch_size: 5
      num_workers: 1
      datasets:
      - type: LJspeechDataset
        args:
          crop_len: 25600
optimizer_generator:
  desc: null
  value:
    type: AdamW
    args:
      lr: 0.0002
      betas:
      - 0.8
      - 0.99
      weight_decay: 0.01
optimizer_discriminator:
  desc: null
  value:
    type: AdamW
    args:
      lr: 0.0002
      betas:
      - 0.8
      - 0.99
      weight_decay: 0.01
loss_generator:
  desc: null
  value:
    type: GeneratorLoss
    args:
      spec_config: {}
      la_mel: 45
      la_fm: 2
loss_discriminator:
  desc: null
  value:
    type: DiscriminatorLoss
    args: {}
metrics:
  desc: null
  value: []
lr_scheduler_generator:
  desc: null
  value:
    type: ExponentialLR
    args:
      gamma: 0.999
lr_scheduler_discriminator:
  desc: null
  value:
    type: ExponentialLR
    args:
      gamma: 0.999
trainer:
  desc: null
  value:
    epochs: 500
    save_dir: saved/
    save_period: 50
    verbosity: 2
    monitor: min val_loss
    early_stop: 100
    visualize: wandb
    wandb_project: Hi-Fi Project
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701392449.770417
    t:
      1:
      - 1
      - 41
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 41
      - 49
      - 51
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
